/**
 * <div id="demo"></div>
 * <script type="text/javascript" src="https://unpkg.com/gd-sprest-bs/dist/gd-sprest-bs-icons.js"></script>
 * <script type="text/javascript">
 *     // Wait for the window to be loaded
 *     window.addEventListener("load", function() {
 *         // Create the icon and append it to the target element
 *         var elIcon = $REST.Icons($REST.IconTypes.Alarm, 32, 32);
 *         document.querySelector("#demo").appendChild(elIcon);
 *     });
 * </script>
*/

/**
 * ### Icons
 * 
 * Renders an icon by type
 * 
 * ```ts
 * import { Icons, IconTypes } from "gd-sprest-bs";
 * 
 * // Create the icon and append it to the target element
 * let elIcon = Icons(IconTypes.Alarm, 32, 32);
 * document.querySelector("#icon").appendChild(elIcon);
 * ```
 */
export const Icons: (iconType:number, height?:number, width?:number) => HTMLElement;

/**
 * Icon Types
*/
export const IconTypes: {
	// alarm-fill.svg
	AlarmFill: number;
	// alarm.svg
	Alarm: number;
	// alt.svg
	Alt: number;
	// app-indicator.svg
	AppIndicator: number;
	// app.svg
	App: number;
	// archive-fill.svg
	ArchiveFill: number;
	// archive.svg
	Archive: number;
	// arrow-90deg-down.svg
	Arrow90degDown: number;
	// arrow-90deg-left.svg
	Arrow90degLeft: number;
	// arrow-90deg-right.svg
	Arrow90degRight: number;
	// arrow-90deg-up.svg
	Arrow90degUp: number;
	// arrow-bar-down.svg
	ArrowBarDown: number;
	// arrow-bar-left.svg
	ArrowBarLeft: number;
	// arrow-bar-right.svg
	ArrowBarRight: number;
	// arrow-bar-up.svg
	ArrowBarUp: number;
	// arrow-clockwise.svg
	ArrowClockwise: number;
	// arrow-counterclockwise.svg
	ArrowCounterclockwise: number;
	// arrow-down-circle-fill.svg
	ArrowDownCircleFill: number;
	// arrow-down-circle.svg
	ArrowDownCircle: number;
	// arrow-down-left-circle-fill.svg
	ArrowDownLeftCircleFill: number;
	// arrow-down-left-circle.svg
	ArrowDownLeftCircle: number;
	// arrow-down-left-square-fill.svg
	ArrowDownLeftSquareFill: number;
	// arrow-down-left-square.svg
	ArrowDownLeftSquare: number;
	// arrow-down-left.svg
	ArrowDownLeft: number;
	// arrow-down-right-circle-fill.svg
	ArrowDownRightCircleFill: number;
	// arrow-down-right-circle.svg
	ArrowDownRightCircle: number;
	// arrow-down-right-square-fill.svg
	ArrowDownRightSquareFill: number;
	// arrow-down-right-square.svg
	ArrowDownRightSquare: number;
	// arrow-down-right.svg
	ArrowDownRight: number;
	// arrow-down-short.svg
	ArrowDownShort: number;
	// arrow-down-square-fill.svg
	ArrowDownSquareFill: number;
	// arrow-down-square.svg
	ArrowDownSquare: number;
	// arrow-down-up.svg
	ArrowDownUp: number;
	// arrow-down.svg
	ArrowDown: number;
	// arrow-left-circle-fill.svg
	ArrowLeftCircleFill: number;
	// arrow-left-circle.svg
	ArrowLeftCircle: number;
	// arrow-left-right.svg
	ArrowLeftRight: number;
	// arrow-left-short.svg
	ArrowLeftShort: number;
	// arrow-left-square-fill.svg
	ArrowLeftSquareFill: number;
	// arrow-left-square.svg
	ArrowLeftSquare: number;
	// arrow-left.svg
	ArrowLeft: number;
	// arrow-repeat.svg
	ArrowRepeat: number;
	// arrow-return-left.svg
	ArrowReturnLeft: number;
	// arrow-return-right.svg
	ArrowReturnRight: number;
	// arrow-right-circle-fill.svg
	ArrowRightCircleFill: number;
	// arrow-right-circle.svg
	ArrowRightCircle: number;
	// arrow-right-short.svg
	ArrowRightShort: number;
	// arrow-right-square-fill.svg
	ArrowRightSquareFill: number;
	// arrow-right-square.svg
	ArrowRightSquare: number;
	// arrow-right.svg
	ArrowRight: number;
	// arrow-up-circle-fill.svg
	ArrowUpCircleFill: number;
	// arrow-up-circle.svg
	ArrowUpCircle: number;
	// arrow-up-left-circle-fill.svg
	ArrowUpLeftCircleFill: number;
	// arrow-up-left-circle.svg
	ArrowUpLeftCircle: number;
	// arrow-up-left-square-fill.svg
	ArrowUpLeftSquareFill: number;
	// arrow-up-left-square.svg
	ArrowUpLeftSquare: number;
	// arrow-up-left.svg
	ArrowUpLeft: number;
	// arrow-up-right-circle-fill.svg
	ArrowUpRightCircleFill: number;
	// arrow-up-right-circle.svg
	ArrowUpRightCircle: number;
	// arrow-up-right-square-fill.svg
	ArrowUpRightSquareFill: number;
	// arrow-up-right-square.svg
	ArrowUpRightSquare: number;
	// arrow-up-right.svg
	ArrowUpRight: number;
	// arrow-up-short.svg
	ArrowUpShort: number;
	// arrow-up-square-fill.svg
	ArrowUpSquareFill: number;
	// arrow-up-square.svg
	ArrowUpSquare: number;
	// arrow-up.svg
	ArrowUp: number;
	// arrows-angle-contract.svg
	ArrowsAngleContract: number;
	// arrows-angle-expand.svg
	ArrowsAngleExpand: number;
	// arrows-collapse.svg
	ArrowsCollapse: number;
	// arrows-expand.svg
	ArrowsExpand: number;
	// arrows-fullscreen.svg
	ArrowsFullscreen: number;
	// arrows-move.svg
	ArrowsMove: number;
	// aspect-ratio-fill.svg
	AspectRatioFill: number;
	// aspect-ratio.svg
	AspectRatio: number;
	// asterisk.svg
	Asterisk: number;
	// at.svg
	At: number;
	// award-fill.svg
	AwardFill: number;
	// award.svg
	Award: number;
	// backspace-fill.svg
	BackspaceFill: number;
	// backspace-reverse-fill.svg
	BackspaceReverseFill: number;
	// backspace-reverse.svg
	BackspaceReverse: number;
	// backspace.svg
	Backspace: number;
	// bag-check.svg
	BagCheck: number;
	// bag-dash.svg
	BagDash: number;
	// bag-fill.svg
	BagFill: number;
	// bag-plus.svg
	BagPlus: number;
	// bag.svg
	Bag: number;
	// bar-chart-fill.svg
	BarChartFill: number;
	// bar-chart.svg
	BarChart: number;
	// basket-fill.svg
	BasketFill: number;
	// basket.svg
	Basket: number;
	// basket2-fill.svg
	Basket2Fill: number;
	// basket2.svg
	Basket2: number;
	// basket3-fill.svg
	Basket3Fill: number;
	// basket3.svg
	Basket3: number;
	// battery-charging.svg
	BatteryCharging: number;
	// battery-full.svg
	BatteryFull: number;
	// battery-half.svg
	BatteryHalf: number;
	// battery.svg
	Battery: number;
	// bell-fill.svg
	BellFill: number;
	// bell.svg
	Bell: number;
	// blockquote-left.svg
	BlockquoteLeft: number;
	// blockquote-right.svg
	BlockquoteRight: number;
	// book-half.svg
	BookHalf: number;
	// book.svg
	Book: number;
	// bookmark-check.svg
	BookmarkCheck: number;
	// bookmark-dash.svg
	BookmarkDash: number;
	// bookmark-fill.svg
	BookmarkFill: number;
	// bookmark-plus.svg
	BookmarkPlus: number;
	// bookmark.svg
	Bookmark: number;
	// bookmarks-fill.svg
	BookmarksFill: number;
	// bookmarks.svg
	Bookmarks: number;
	// bootstrap-fill.svg
	BootstrapFill: number;
	// bootstrap-reboot.svg
	BootstrapReboot: number;
	// bootstrap.svg
	Bootstrap: number;
	// bounding-box-circles.svg
	BoundingBoxCircles: number;
	// bounding-box.svg
	BoundingBox: number;
	// box-arrow-down-left.svg
	BoxArrowDownLeft: number;
	// box-arrow-down-right.svg
	BoxArrowDownRight: number;
	// box-arrow-down.svg
	BoxArrowDown: number;
	// box-arrow-in-down-left.svg
	BoxArrowInDownLeft: number;
	// box-arrow-in-down-right.svg
	BoxArrowInDownRight: number;
	// box-arrow-in-down.svg
	BoxArrowInDown: number;
	// box-arrow-in-left.svg
	BoxArrowInLeft: number;
	// box-arrow-in-right.svg
	BoxArrowInRight: number;
	// box-arrow-in-up-left.svg
	BoxArrowInUpLeft: number;
	// box-arrow-in-up-right.svg
	BoxArrowInUpRight: number;
	// box-arrow-in-up.svg
	BoxArrowInUp: number;
	// box-arrow-left.svg
	BoxArrowLeft: number;
	// box-arrow-right.svg
	BoxArrowRight: number;
	// box-arrow-up-left.svg
	BoxArrowUpLeft: number;
	// box-arrow-up-right.svg
	BoxArrowUpRight: number;
	// box-arrow-up.svg
	BoxArrowUp: number;
	// box-seam.svg
	BoxSeam: number;
	// box.svg
	Box: number;
	// braces.svg
	Braces: number;
	// briefcase-fill.svg
	BriefcaseFill: number;
	// briefcase.svg
	Briefcase: number;
	// brightness-alt-high-fill.svg
	BrightnessAltHighFill: number;
	// brightness-alt-high.svg
	BrightnessAltHigh: number;
	// brightness-alt-low-fill.svg
	BrightnessAltLowFill: number;
	// brightness-alt-low.svg
	BrightnessAltLow: number;
	// brightness-high-fill.svg
	BrightnessHighFill: number;
	// brightness-high.svg
	BrightnessHigh: number;
	// brightness-low-fill.svg
	BrightnessLowFill: number;
	// brightness-low.svg
	BrightnessLow: number;
	// brush.svg
	Brush: number;
	// bucket-fill.svg
	BucketFill: number;
	// bucket.svg
	Bucket: number;
	// building.svg
	Building: number;
	// bullseye.svg
	Bullseye: number;
	// calendar-check-fill.svg
	CalendarCheckFill: number;
	// calendar-check.svg
	CalendarCheck: number;
	// calendar-date-fill.svg
	CalendarDateFill: number;
	// calendar-date.svg
	CalendarDate: number;
	// calendar-day-fill.svg
	CalendarDayFill: number;
	// calendar-day.svg
	CalendarDay: number;
	// calendar-fill.svg
	CalendarFill: number;
	// calendar-minus-fill.svg
	CalendarMinusFill: number;
	// calendar-minus.svg
	CalendarMinus: number;
	// calendar-month-fill.svg
	CalendarMonthFill: number;
	// calendar-month.svg
	CalendarMonth: number;
	// calendar-plus-fill.svg
	CalendarPlusFill: number;
	// calendar-plus.svg
	CalendarPlus: number;
	// calendar.svg
	Calendar: number;
	// calendar2-check-fill.svg
	Calendar2CheckFill: number;
	// calendar2-check.svg
	Calendar2Check: number;
	// calendar2-date-fill.svg
	Calendar2DateFill: number;
	// calendar2-date.svg
	Calendar2Date: number;
	// calendar2-day-fill.svg
	Calendar2DayFill: number;
	// calendar2-day.svg
	Calendar2Day: number;
	// calendar2-fill.svg
	Calendar2Fill: number;
	// calendar2-minus-fill.svg
	Calendar2MinusFill: number;
	// calendar2-minus.svg
	Calendar2Minus: number;
	// calendar2-month-fill.svg
	Calendar2MonthFill: number;
	// calendar2-month.svg
	Calendar2Month: number;
	// calendar2-plus-fill.svg
	Calendar2PlusFill: number;
	// calendar2-plus.svg
	Calendar2Plus: number;
	// calendar2.svg
	Calendar2: number;
	// calendar3-fill.svg
	Calendar3Fill: number;
	// calendar3.svg
	Calendar3: number;
	// calendar4.svg
	Calendar4: number;
	// camera-video-fill.svg
	CameraVideoFill: number;
	// camera-video-off-fill.svg
	CameraVideoOffFill: number;
	// camera-video-off.svg
	CameraVideoOff: number;
	// camera-video.svg
	CameraVideo: number;
	// camera.svg
	Camera: number;
	// capslock-fill.svg
	CapslockFill: number;
	// capslock.svg
	Capslock: number;
	// card-checklist.svg
	CardChecklist: number;
	// card-heading.svg
	CardHeading: number;
	// card-image.svg
	CardImage: number;
	// card-list.svg
	CardList: number;
	// card-text.svg
	CardText: number;
	// caret-down-fill.svg
	CaretDownFill: number;
	// caret-down-square-fill.svg
	CaretDownSquareFill: number;
	// caret-down-square.svg
	CaretDownSquare: number;
	// caret-down.svg
	CaretDown: number;
	// caret-left-fill.svg
	CaretLeftFill: number;
	// caret-left-square-fill.svg
	CaretLeftSquareFill: number;
	// caret-left-square.svg
	CaretLeftSquare: number;
	// caret-left.svg
	CaretLeft: number;
	// caret-right-fill.svg
	CaretRightFill: number;
	// caret-right-square-fill.svg
	CaretRightSquareFill: number;
	// caret-right-square.svg
	CaretRightSquare: number;
	// caret-right.svg
	CaretRight: number;
	// caret-up-fill.svg
	CaretUpFill: number;
	// caret-up-square-fill.svg
	CaretUpSquareFill: number;
	// caret-up-square.svg
	CaretUpSquare: number;
	// caret-up.svg
	CaretUp: number;
	// cart-check.svg
	CartCheck: number;
	// cart-dash.svg
	CartDash: number;
	// cart-fill.svg
	CartFill: number;
	// cart-plus.svg
	CartPlus: number;
	// cart.svg
	Cart: number;
	// cart2.svg
	Cart2: number;
	// cart3.svg
	Cart3: number;
	// cart4.svg
	Cart4: number;
	// chat-dots-fill.svg
	ChatDotsFill: number;
	// chat-dots.svg
	ChatDots: number;
	// chat-fill.svg
	ChatFill: number;
	// chat-quote-fill.svg
	ChatQuoteFill: number;
	// chat-quote.svg
	ChatQuote: number;
	// chat-square-dots-fill.svg
	ChatSquareDotsFill: number;
	// chat-square-dots.svg
	ChatSquareDots: number;
	// chat-square-fill.svg
	ChatSquareFill: number;
	// chat-square-quote-fill.svg
	ChatSquareQuoteFill: number;
	// chat-square-quote.svg
	ChatSquareQuote: number;
	// chat-square.svg
	ChatSquare: number;
	// chat.svg
	Chat: number;
	// check-all.svg
	CheckAll: number;
	// check-circle-fill.svg
	CheckCircleFill: number;
	// check-circle.svg
	CheckCircle: number;
	// check-square-fill.svg
	CheckSquareFill: number;
	// check-square.svg
	CheckSquare: number;
	// check.svg
	Check: number;
	// check2-all.svg
	Check2All: number;
	// check2-circle.svg
	Check2Circle: number;
	// check2-square.svg
	Check2Square: number;
	// check2.svg
	Check2: number;
	// chevron-bar-contract.svg
	ChevronBarContract: number;
	// chevron-bar-down.svg
	ChevronBarDown: number;
	// chevron-bar-expand.svg
	ChevronBarExpand: number;
	// chevron-bar-left.svg
	ChevronBarLeft: number;
	// chevron-bar-right.svg
	ChevronBarRight: number;
	// chevron-bar-up.svg
	ChevronBarUp: number;
	// chevron-compact-down.svg
	ChevronCompactDown: number;
	// chevron-compact-left.svg
	ChevronCompactLeft: number;
	// chevron-compact-right.svg
	ChevronCompactRight: number;
	// chevron-compact-up.svg
	ChevronCompactUp: number;
	// chevron-contract.svg
	ChevronContract: number;
	// chevron-double-down.svg
	ChevronDoubleDown: number;
	// chevron-double-left.svg
	ChevronDoubleLeft: number;
	// chevron-double-right.svg
	ChevronDoubleRight: number;
	// chevron-double-up.svg
	ChevronDoubleUp: number;
	// chevron-down.svg
	ChevronDown: number;
	// chevron-expand.svg
	ChevronExpand: number;
	// chevron-left.svg
	ChevronLeft: number;
	// chevron-right.svg
	ChevronRight: number;
	// chevron-up.svg
	ChevronUp: number;
	// circle-fill.svg
	CircleFill: number;
	// circle-half.svg
	CircleHalf: number;
	// circle-square.svg
	CircleSquare: number;
	// circle.svg
	Circle: number;
	// clipboard-data.svg
	ClipboardData: number;
	// clipboard.svg
	Clipboard: number;
	// clock-fill.svg
	ClockFill: number;
	// clock-history.svg
	ClockHistory: number;
	// clock.svg
	Clock: number;
	// cloud-download.svg
	CloudDownload: number;
	// cloud-fill.svg
	CloudFill: number;
	// cloud-slash-fill.svg
	CloudSlashFill: number;
	// cloud-slash.svg
	CloudSlash: number;
	// cloud-upload.svg
	CloudUpload: number;
	// cloud.svg
	Cloud: number;
	// code-slash.svg
	CodeSlash: number;
	// code.svg
	Code: number;
	// collection-fill.svg
	CollectionFill: number;
	// collection-play-fill.svg
	CollectionPlayFill: number;
	// collection-play.svg
	CollectionPlay: number;
	// collection.svg
	Collection: number;
	// columns-gap.svg
	ColumnsGap: number;
	// columns.svg
	Columns: number;
	// command.svg
	Command: number;
	// compass.svg
	Compass: number;
	// cone-striped.svg
	ConeStriped: number;
	// cone.svg
	Cone: number;
	// controller.svg
	Controller: number;
	// credit-card.svg
	CreditCard: number;
	// crop.svg
	Crop: number;
	// cup.svg
	Cup: number;
	// cursor-fill.svg
	CursorFill: number;
	// cursor-text.svg
	CursorText: number;
	// cursor.svg
	Cursor: number;
	// dash-circle-fill.svg
	DashCircleFill: number;
	// dash-circle.svg
	DashCircle: number;
	// dash-square-fill.svg
	DashSquareFill: number;
	// dash-square.svg
	DashSquare: number;
	// dash.svg
	Dash: number;
	// diamond-fill.svg
	DiamondFill: number;
	// diamond-half.svg
	DiamondHalf: number;
	// diamond.svg
	Diamond: number;
	// display-fill.svg
	DisplayFill: number;
	// display.svg
	Display: number;
	// door-closed-fill.svg
	DoorClosedFill: number;
	// door-closed.svg
	DoorClosed: number;
	// dot.svg
	Dot: number;
	// download.svg
	Download: number;
	// droplet-fill.svg
	DropletFill: number;
	// droplet-half.svg
	DropletHalf: number;
	// droplet.svg
	Droplet: number;
	// egg-fill.svg
	EggFill: number;
	// egg-fried.svg
	EggFried: number;
	// egg.svg
	Egg: number;
	// eject-fill.svg
	EjectFill: number;
	// eject.svg
	Eject: number;
	// emoji-angry.svg
	EmojiAngry: number;
	// emoji-dizzy.svg
	EmojiDizzy: number;
	// emoji-frown.svg
	EmojiFrown: number;
	// emoji-laughing.svg
	EmojiLaughing: number;
	// emoji-neutral.svg
	EmojiNeutral: number;
	// emoji-smile-upside-down.svg
	EmojiSmileUpsideDown: number;
	// emoji-smile.svg
	EmojiSmile: number;
	// emoji-sunglasses.svg
	EmojiSunglasses: number;
	// envelope-fill.svg
	EnvelopeFill: number;
	// envelope-open-fill.svg
	EnvelopeOpenFill: number;
	// envelope-open.svg
	EnvelopeOpen: number;
	// envelope.svg
	Envelope: number;
	// exclamation-circle-fill.svg
	ExclamationCircleFill: number;
	// exclamation-circle.svg
	ExclamationCircle: number;
	// exclamation-diamond-fill.svg
	ExclamationDiamondFill: number;
	// exclamation-diamond.svg
	ExclamationDiamond: number;
	// exclamation-octagon-fill.svg
	ExclamationOctagonFill: number;
	// exclamation-octagon.svg
	ExclamationOctagon: number;
	// exclamation-square-fill.svg
	ExclamationSquareFill: number;
	// exclamation-square.svg
	ExclamationSquare: number;
	// exclamation-triangle-fill.svg
	ExclamationTriangleFill: number;
	// exclamation-triangle.svg
	ExclamationTriangle: number;
	// exclamation.svg
	Exclamation: number;
	// exclude.svg
	Exclude: number;
	// eye-fill.svg
	EyeFill: number;
	// eye-slash-fill.svg
	EyeSlashFill: number;
	// eye-slash.svg
	EyeSlash: number;
	// eye.svg
	Eye: number;
	// file-arrow-down.svg
	FileArrowDown: number;
	// file-arrow-up.svg
	FileArrowUp: number;
	// file-break.svg
	FileBreak: number;
	// file-check.svg
	FileCheck: number;
	// file-code.svg
	FileCode: number;
	// file-diff.svg
	FileDiff: number;
	// file-earmark-arrow-down.svg
	FileEarmarkArrowDown: number;
	// file-earmark-arrow-up.svg
	FileEarmarkArrowUp: number;
	// file-earmark-break.svg
	FileEarmarkBreak: number;
	// file-earmark-check.svg
	FileEarmarkCheck: number;
	// file-earmark-code.svg
	FileEarmarkCode: number;
	// file-earmark-diff.svg
	FileEarmarkDiff: number;
	// file-earmark-minus.svg
	FileEarmarkMinus: number;
	// file-earmark-plus.svg
	FileEarmarkPlus: number;
	// file-earmark-ruled.svg
	FileEarmarkRuled: number;
	// file-earmark-spreadsheet.svg
	FileEarmarkSpreadsheet: number;
	// file-earmark-text.svg
	FileEarmarkText: number;
	// file-earmark-zip.svg
	FileEarmarkZip: number;
	// file-earmark.svg
	FileEarmark: number;
	// file-minus.svg
	FileMinus: number;
	// file-plus.svg
	FilePlus: number;
	// file-post.svg
	FilePost: number;
	// file-richtext.svg
	FileRichtext: number;
	// file-ruled.svg
	FileRuled: number;
	// file-spreadsheet.svg
	FileSpreadsheet: number;
	// file-text.svg
	FileText: number;
	// file-zip.svg
	FileZip: number;
	// file.svg
	File: number;
	// files-alt.svg
	FilesAlt: number;
	// files.svg
	Files: number;
	// film.svg
	Film: number;
	// filter-left.svg
	FilterLeft: number;
	// filter-right.svg
	FilterRight: number;
	// filter.svg
	Filter: number;
	// flag-fill.svg
	FlagFill: number;
	// flag.svg
	Flag: number;
	// folder-check.svg
	FolderCheck: number;
	// folder-fill.svg
	FolderFill: number;
	// folder-minus.svg
	FolderMinus: number;
	// folder-plus.svg
	FolderPlus: number;
	// folder-symlink-fill.svg
	FolderSymlinkFill: number;
	// folder-symlink.svg
	FolderSymlink: number;
	// folder.svg
	Folder: number;
	// fonts.svg
	Fonts: number;
	// forward-fill.svg
	ForwardFill: number;
	// forward.svg
	Forward: number;
	// fullscreen-exit.svg
	FullscreenExit: number;
	// fullscreen.svg
	Fullscreen: number;
	// funnel-fill.svg
	FunnelFill: number;
	// funnel.svg
	Funnel: number;
	// gear-fill.svg
	GearFill: number;
	// gear-wide-connected.svg
	GearWideConnected: number;
	// gear-wide.svg
	GearWide: number;
	// gear.svg
	Gear: number;
	// gem.svg
	Gem: number;
	// geo-alt.svg
	GeoAlt: number;
	// geo.svg
	Geo: number;
	// gift-fill.svg
	GiftFill: number;
	// gift.svg
	Gift: number;
	// graph-down.svg
	GraphDown: number;
	// graph-up.svg
	GraphUp: number;
	// grid-1x2-fill.svg
	Grid1x2Fill: number;
	// grid-1x2.svg
	Grid1x2: number;
	// grid-3x2-gap-fill.svg
	Grid3x2GapFill: number;
	// grid-3x2-gap.svg
	Grid3x2Gap: number;
	// grid-3x2.svg
	Grid3x2: number;
	// grid-3x3-gap-fill.svg
	Grid3x3GapFill: number;
	// grid-3x3-gap.svg
	Grid3x3Gap: number;
	// grid-3x3.svg
	Grid3x3: number;
	// grid-fill.svg
	GridFill: number;
	// grid.svg
	Grid: number;
	// grip-horizontal.svg
	GripHorizontal: number;
	// grip-vertical.svg
	GripVertical: number;
	// hammer.svg
	Hammer: number;
	// hand-index-thumb.svg
	HandIndexThumb: number;
	// hand-index.svg
	HandIndex: number;
	// hand-thumbs-down.svg
	HandThumbsDown: number;
	// hand-thumbs-up.svg
	HandThumbsUp: number;
	// handbag-fill.svg
	HandbagFill: number;
	// handbag.svg
	Handbag: number;
	// hash.svg
	Hash: number;
	// headphones.svg
	Headphones: number;
	// heart-fill.svg
	HeartFill: number;
	// heart-half.svg
	HeartHalf: number;
	// heart.svg
	Heart: number;
	// hexagon-fill.svg
	HexagonFill: number;
	// hexagon-half.svg
	HexagonHalf: number;
	// hexagon.svg
	Hexagon: number;
	// house-door-fill.svg
	HouseDoorFill: number;
	// house-door.svg
	HouseDoor: number;
	// house-fill.svg
	HouseFill: number;
	// house.svg
	House: number;
	// hr.svg
	Hr: number;
	// image-alt.svg
	ImageAlt: number;
	// image-fill.svg
	ImageFill: number;
	// image.svg
	Image: number;
	// images.svg
	Images: number;
	// inbox-fill.svg
	InboxFill: number;
	// inbox.svg
	Inbox: number;
	// inboxes-fill.svg
	InboxesFill: number;
	// inboxes.svg
	Inboxes: number;
	// info-circle-fill.svg
	InfoCircleFill: number;
	// info-circle.svg
	InfoCircle: number;
	// info-square-fill.svg
	InfoSquareFill: number;
	// info-square.svg
	InfoSquare: number;
	// info.svg
	Info: number;
	// intersect.svg
	Intersect: number;
	// justify-left.svg
	JustifyLeft: number;
	// justify-right.svg
	JustifyRight: number;
	// justify.svg
	Justify: number;
	// kanban-fill.svg
	KanbanFill: number;
	// kanban.svg
	Kanban: number;
	// laptop.svg
	Laptop: number;
	// layers-fill.svg
	LayersFill: number;
	// layers-half.svg
	LayersHalf: number;
	// layers.svg
	Layers: number;
	// layout-sidebar-inset-reverse.svg
	LayoutSidebarInsetReverse: number;
	// layout-sidebar-inset.svg
	LayoutSidebarInset: number;
	// layout-sidebar-reverse.svg
	LayoutSidebarReverse: number;
	// layout-sidebar.svg
	LayoutSidebar: number;
	// layout-split.svg
	LayoutSplit: number;
	// layout-text-sidebar-reverse.svg
	LayoutTextSidebarReverse: number;
	// layout-text-sidebar.svg
	LayoutTextSidebar: number;
	// layout-text-window-reverse.svg
	LayoutTextWindowReverse: number;
	// layout-text-window.svg
	LayoutTextWindow: number;
	// layout-three-columns.svg
	LayoutThreeColumns: number;
	// layout-wtf.svg
	LayoutWtf: number;
	// life-preserver.svg
	LifePreserver: number;
	// lightning-fill.svg
	LightningFill: number;
	// lightning.svg
	Lightning: number;
	// link-45deg.svg
	Link45deg: number;
	// link.svg
	Link: number;
	// list-check.svg
	ListCheck: number;
	// list-nested.svg
	ListNested: number;
	// list-ol.svg
	ListOl: number;
	// list-task.svg
	ListTask: number;
	// list-ul.svg
	ListUl: number;
	// list.svg
	List: number;
	// lock-fill.svg
	LockFill: number;
	// lock.svg
	Lock: number;
	// map.svg
	Map: number;
	// mic-fill.svg
	MicFill: number;
	// mic-mute-fill.svg
	MicMuteFill: number;
	// mic-mute.svg
	MicMute: number;
	// mic.svg
	Mic: number;
	// minecart-loaded.svg
	MinecartLoaded: number;
	// minecart.svg
	Minecart: number;
	// moon.svg
	Moon: number;
	// music-note-beamed.svg
	MusicNoteBeamed: number;
	// music-note-list.svg
	MusicNoteList: number;
	// music-note.svg
	MusicNote: number;
	// music-player-fill.svg
	MusicPlayerFill: number;
	// music-player.svg
	MusicPlayer: number;
	// newspaper.svg
	Newspaper: number;
	// octagon-fill.svg
	OctagonFill: number;
	// octagon-half.svg
	OctagonHalf: number;
	// octagon.svg
	Octagon: number;
	// option.svg
	Option: number;
	// outlet.svg
	Outlet: number;
	// paperclip.svg
	Paperclip: number;
	// pause-fill.svg
	PauseFill: number;
	// pause.svg
	Pause: number;
	// pen.svg
	Pen: number;
	// pencil-square.svg
	PencilSquare: number;
	// pencil.svg
	Pencil: number;
	// pentagon-fill.svg
	PentagonFill: number;
	// pentagon-half.svg
	PentagonHalf: number;
	// pentagon.svg
	Pentagon: number;
	// people-fill.svg
	PeopleFill: number;
	// people.svg
	People: number;
	// person-bounding-box.svg
	PersonBoundingBox: number;
	// person-check-fill.svg
	PersonCheckFill: number;
	// person-check.svg
	PersonCheck: number;
	// person-circle.svg
	PersonCircle: number;
	// person-dash-fill.svg
	PersonDashFill: number;
	// person-dash.svg
	PersonDash: number;
	// person-fill.svg
	PersonFill: number;
	// person-lines-fill.svg
	PersonLinesFill: number;
	// person-plus-fill.svg
	PersonPlusFill: number;
	// person-plus.svg
	PersonPlus: number;
	// person-square.svg
	PersonSquare: number;
	// person.svg
	Person: number;
	// phone-landscape.svg
	PhoneLandscape: number;
	// phone.svg
	Phone: number;
	// pie-chart-fill.svg
	PieChartFill: number;
	// pie-chart.svg
	PieChart: number;
	// pip-fill.svg
	PipFill: number;
	// pip.svg
	Pip: number;
	// play-fill.svg
	PlayFill: number;
	// play.svg
	Play: number;
	// plug.svg
	Plug: number;
	// plus-circle-fill.svg
	PlusCircleFill: number;
	// plus-circle.svg
	PlusCircle: number;
	// plus-square-fill.svg
	PlusSquareFill: number;
	// plus-square.svg
	PlusSquare: number;
	// plus.svg
	Plus: number;
	// power.svg
	Power: number;
	// puzzle-fill.svg
	PuzzleFill: number;
	// puzzle.svg
	Puzzle: number;
	// question-circle-fill.svg
	QuestionCircleFill: number;
	// question-circle.svg
	QuestionCircle: number;
	// question-diamond-fill.svg
	QuestionDiamondFill: number;
	// question-diamond.svg
	QuestionDiamond: number;
	// question-octagon-fill.svg
	QuestionOctagonFill: number;
	// question-octagon.svg
	QuestionOctagon: number;
	// question-square-fill.svg
	QuestionSquareFill: number;
	// question-square.svg
	QuestionSquare: number;
	// question.svg
	Question: number;
	// receipt-cutoff.svg
	ReceiptCutoff: number;
	// receipt.svg
	Receipt: number;
	// reply-all-fill.svg
	ReplyAllFill: number;
	// reply-all.svg
	ReplyAll: number;
	// reply-fill.svg
	ReplyFill: number;
	// reply.svg
	Reply: number;
	// screwdriver.svg
	Screwdriver: number;
	// search.svg
	Search: number;
	// server.svg
	Server: number;
	// shield-fill.svg
	ShieldFill: number;
	// shield-lock-fill.svg
	ShieldLockFill: number;
	// shield-lock.svg
	ShieldLock: number;
	// shield-shaded.svg
	ShieldShaded: number;
	// shield-slash-fill.svg
	ShieldSlashFill: number;
	// shield-slash.svg
	ShieldSlash: number;
	// shield.svg
	Shield: number;
	// shift-fill.svg
	ShiftFill: number;
	// shift.svg
	Shift: number;
	// shop-window.svg
	ShopWindow: number;
	// shop.svg
	Shop: number;
	// shuffle.svg
	Shuffle: number;
	// skip-backward-fill.svg
	SkipBackwardFill: number;
	// skip-backward.svg
	SkipBackward: number;
	// skip-end-fill.svg
	SkipEndFill: number;
	// skip-end.svg
	SkipEnd: number;
	// skip-forward-fill.svg
	SkipForwardFill: number;
	// skip-forward.svg
	SkipForward: number;
	// skip-start-fill.svg
	SkipStartFill: number;
	// skip-start.svg
	SkipStart: number;
	// slash-circle-fill.svg
	SlashCircleFill: number;
	// slash-circle.svg
	SlashCircle: number;
	// slash-square-fill.svg
	SlashSquareFill: number;
	// slash-square.svg
	SlashSquare: number;
	// slash.svg
	Slash: number;
	// sliders.svg
	Sliders: number;
	// soundwave.svg
	Soundwave: number;
	// speaker.svg
	Speaker: number;
	// square-fill.svg
	SquareFill: number;
	// square-half.svg
	SquareHalf: number;
	// square.svg
	Square: number;
	// star-fill.svg
	StarFill: number;
	// star-half.svg
	StarHalf: number;
	// star.svg
	Star: number;
	// stop-fill.svg
	StopFill: number;
	// stop.svg
	Stop: number;
	// stopwatch-fill.svg
	StopwatchFill: number;
	// stopwatch.svg
	Stopwatch: number;
	// subtract.svg
	Subtract: number;
	// sun.svg
	Sun: number;
	// table.svg
	Table: number;
	// tablet-landscape.svg
	TabletLandscape: number;
	// tablet.svg
	Tablet: number;
	// tag-fill.svg
	TagFill: number;
	// tag.svg
	Tag: number;
	// terminal-fill.svg
	TerminalFill: number;
	// terminal.svg
	Terminal: number;
	// text-center.svg
	TextCenter: number;
	// text-indent-left.svg
	TextIndentLeft: number;
	// text-indent-right.svg
	TextIndentRight: number;
	// text-left.svg
	TextLeft: number;
	// text-right.svg
	TextRight: number;
	// textarea-t.svg
	TextareaT: number;
	// textarea.svg
	Textarea: number;
	// three-dots-vertical.svg
	ThreeDotsVertical: number;
	// three-dots.svg
	ThreeDots: number;
	// toggle-off.svg
	ToggleOff: number;
	// toggle-on.svg
	ToggleOn: number;
	// toggles.svg
	Toggles: number;
	// tools.svg
	Tools: number;
	// trash-fill.svg
	TrashFill: number;
	// trash.svg
	Trash: number;
	// trash2-fill.svg
	Trash2Fill: number;
	// trash2.svg
	Trash2: number;
	// triangle-fill.svg
	TriangleFill: number;
	// triangle-half.svg
	TriangleHalf: number;
	// triangle.svg
	Triangle: number;
	// trophy.svg
	Trophy: number;
	// truck-flatbed.svg
	TruckFlatbed: number;
	// truck.svg
	Truck: number;
	// tv-fill.svg
	TvFill: number;
	// tv.svg
	Tv: number;
	// type-bold.svg
	TypeBold: number;
	// type-h1.svg
	TypeH1: number;
	// type-h2.svg
	TypeH2: number;
	// type-h3.svg
	TypeH3: number;
	// type-italic.svg
	TypeItalic: number;
	// type-strikethrough.svg
	TypeStrikethrough: number;
	// type-underline.svg
	TypeUnderline: number;
	// type.svg
	Type: number;
	// union.svg
	Union: number;
	// unlock-fill.svg
	UnlockFill: number;
	// unlock.svg
	Unlock: number;
	// upc-scan.svg
	UpcScan: number;
	// upc.svg
	Upc: number;
	// upload.svg
	Upload: number;
	// view-list.svg
	ViewList: number;
	// view-stacked.svg
	ViewStacked: number;
	// volume-down-fill.svg
	VolumeDownFill: number;
	// volume-down.svg
	VolumeDown: number;
	// volume-mute-fill.svg
	VolumeMuteFill: number;
	// volume-mute.svg
	VolumeMute: number;
	// volume-off-fill.svg
	VolumeOffFill: number;
	// volume-off.svg
	VolumeOff: number;
	// volume-up-fill.svg
	VolumeUpFill: number;
	// volume-up.svg
	VolumeUp: number;
	// vr.svg
	Vr: number;
	// wallet.svg
	Wallet: number;
	// wallet2.svg
	Wallet2: number;
	// watch.svg
	Watch: number;
	// wifi.svg
	Wifi: number;
	// window.svg
	Window: number;
	// wrench.svg
	Wrench: number;
	// x-circle-fill.svg
	XCircleFill: number;
	// x-circle.svg
	XCircle: number;
	// x-diamond-fill.svg
	XDiamondFill: number;
	// x-diamond.svg
	XDiamond: number;
	// x-octagon-fill.svg
	XOctagonFill: number;
	// x-octagon.svg
	XOctagon: number;
	// x-square-fill.svg
	XSquareFill: number;
	// x-square.svg
	XSquare: number;
	// x.svg
	X: number;
}