
// Renders an icon by type
export const Icons = (iconType:number, height?:number, width?:number) => HTMLElement;

// Icon Types
export const IconTypes: {
	// alarm-fill.svg
	alarmFill: number;
	// alarm.svg
	alarm: number;
	// alert-circle-fill.svg
	alertCircleFill: number;
	// alert-circle.svg
	alertCircle: number;
	// alert-octagon-fill.svg
	alertOctagonFill: number;
	// alert-octagon.svg
	alertOctagon: number;
	// alert-square-fill.svg
	alertSquareFill: number;
	// alert-square.svg
	alertSquare: number;
	// alert-triangle-fill.svg
	alertTriangleFill: number;
	// alert-triangle.svg
	alertTriangle: number;
	// archive-fill.svg
	archiveFill: number;
	// archive.svg
	archive: number;
	// arrow-bar-bottom.svg
	arrowBarBottom: number;
	// arrow-bar-left.svg
	arrowBarLeft: number;
	// arrow-bar-right.svg
	arrowBarRight: number;
	// arrow-bar-up.svg
	arrowBarUp: number;
	// arrow-clockwise.svg
	arrowClockwise: number;
	// arrow-counterclockwise.svg
	arrowCounterclockwise: number;
	// arrow-down-left.svg
	arrowDownLeft: number;
	// arrow-down-right.svg
	arrowDownRight: number;
	// arrow-down-short.svg
	arrowDownShort: number;
	// arrow-down.svg
	arrowDown: number;
	// arrow-left-right.svg
	arrowLeftRight: number;
	// arrow-left-short.svg
	arrowLeftShort: number;
	// arrow-left.svg
	arrowLeft: number;
	// arrow-repeat.svg
	arrowRepeat: number;
	// arrow-right-short.svg
	arrowRightShort: number;
	// arrow-right.svg
	arrowRight: number;
	// arrow-up-down.svg
	arrowUpDown: number;
	// arrow-up-left.svg
	arrowUpLeft: number;
	// arrow-up-right.svg
	arrowUpRight: number;
	// arrow-up-short.svg
	arrowUpShort: number;
	// arrow-up.svg
	arrowUp: number;
	// arrows-angle-contract.svg
	arrowsAngleContract: number;
	// arrows-angle-expand.svg
	arrowsAngleExpand: number;
	// arrows-collapse.svg
	arrowsCollapse: number;
	// arrows-expand.svg
	arrowsExpand: number;
	// arrows-fullscreen.svg
	arrowsFullscreen: number;
	// at.svg
	at: number;
	// award.svg
	award: number;
	// backspace-fill.svg
	backspaceFill: number;
	// backspace-reverse-fill.svg
	backspaceReverseFill: number;
	// backspace-reverse.svg
	backspaceReverse: number;
	// backspace.svg
	backspace: number;
	// bar-chart-fill.svg
	barChartFill: number;
	// bar-chart.svg
	barChart: number;
	// battery-charging.svg
	batteryCharging: number;
	// battery-full.svg
	batteryFull: number;
	// battery.svg
	battery: number;
	// bell-fill.svg
	bellFill: number;
	// bell.svg
	bell: number;
	// blockquote-left.svg
	blockquoteLeft: number;
	// blockquote-right.svg
	blockquoteRight: number;
	// book-half-fill.svg
	bookHalfFill: number;
	// book.svg
	book: number;
	// bookmark-fill.svg
	bookmarkFill: number;
	// bookmark.svg
	bookmark: number;
	// bootstrap-fill.svg
	bootstrapFill: number;
	// bootstrap-reboot.svg
	bootstrapReboot: number;
	// bootstrap.svg
	bootstrap: number;
	// box-arrow-bottom-left.svg
	boxArrowBottomLeft: number;
	// box-arrow-bottom-right.svg
	boxArrowBottomRight: number;
	// box-arrow-down.svg
	boxArrowDown: number;
	// box-arrow-left.svg
	boxArrowLeft: number;
	// box-arrow-right.svg
	boxArrowRight: number;
	// box-arrow-up-left.svg
	boxArrowUpLeft: number;
	// box-arrow-up-right.svg
	boxArrowUpRight: number;
	// box-arrow-up.svg
	boxArrowUp: number;
	// braces.svg
	braces: number;
	// brightness-fill-high.svg
	brightnessFillHigh: number;
	// brightness-fill-low.svg
	brightnessFillLow: number;
	// brightness-high.svg
	brightnessHigh: number;
	// brightness-low.svg
	brightnessLow: number;
	// brush.svg
	brush: number;
	// bucket-fill.svg
	bucketFill: number;
	// bucket.svg
	bucket: number;
	// building.svg
	building: number;
	// bullseye.svg
	bullseye: number;
	// calendar-fill.svg
	calendarFill: number;
	// calendar.svg
	calendar: number;
	// camera-video-fill.svg
	cameraVideoFill: number;
	// camera-video.svg
	cameraVideo: number;
	// camera.svg
	camera: number;
	// capslock-fill.svg
	capslockFill: number;
	// capslock.svg
	capslock: number;
	// chat-fill.svg
	chatFill: number;
	// chat.svg
	chat: number;
	// check-box.svg
	checkBox: number;
	// check-circle.svg
	checkCircle: number;
	// check.svg
	check: number;
	// chevron-compact-down.svg
	chevronCompactDown: number;
	// chevron-compact-left.svg
	chevronCompactLeft: number;
	// chevron-compact-right.svg
	chevronCompactRight: number;
	// chevron-compact-up.svg
	chevronCompactUp: number;
	// chevron-down.svg
	chevronDown: number;
	// chevron-left.svg
	chevronLeft: number;
	// chevron-right.svg
	chevronRight: number;
	// chevron-up.svg
	chevronUp: number;
	// circle-fill.svg
	circleFill: number;
	// circle-half.svg
	circleHalf: number;
	// circle-slash.svg
	circleSlash: number;
	// circle.svg
	circle: number;
	// clock-fill.svg
	clockFill: number;
	// clock.svg
	clock: number;
	// cloud-download.svg
	cloudDownload: number;
	// cloud-fill.svg
	cloudFill: number;
	// cloud-upload.svg
	cloudUpload: number;
	// cloud.svg
	cloud: number;
	// code-slash.svg
	codeSlash: number;
	// code.svg
	code: number;
	// columns-gutters.svg
	columnsGutters: number;
	// columns.svg
	columns: number;
	// command.svg
	command: number;
	// compass.svg
	compass: number;
	// cone-striped.svg
	coneStriped: number;
	// cone.svg
	cone: number;
	// controller.svg
	controller: number;
	// credit-card.svg
	creditCard: number;
	// cursor-fill.svg
	cursorFill: number;
	// cursor.svg
	cursor: number;
	// dash.svg
	dash: number;
	// diamond-half.svg
	diamondHalf: number;
	// diamond.svg
	diamond: number;
	// display-fill.svg
	displayFill: number;
	// display.svg
	display: number;
	// document-code.svg
	documentCode: number;
	// document-diff.svg
	documentDiff: number;
	// document-richtext.svg
	documentRichtext: number;
	// document-spreadsheet.svg
	documentSpreadsheet: number;
	// document-text.svg
	documentText: number;
	// document.svg
	document: number;
	// documents-alt.svg
	documentsAlt: number;
	// documents.svg
	documents: number;
	// dot.svg
	dot: number;
	// download.svg
	download: number;
	// egg-fried.svg
	eggFried: number;
	// eject-fill.svg
	ejectFill: number;
	// eject.svg
	eject: number;
	// envelope-fill.svg
	envelopeFill: number;
	// envelope-open-fill.svg
	envelopeOpenFill: number;
	// envelope-open.svg
	envelopeOpen: number;
	// envelope.svg
	envelope: number;
	// eye-fill.svg
	eyeFill: number;
	// eye-slash-fill.svg
	eyeSlashFill: number;
	// eye-slash.svg
	eyeSlash: number;
	// eye.svg
	eye: number;
	// filter.svg
	filter: number;
	// flag-fill.svg
	flagFill: number;
	// flag.svg
	flag: number;
	// folder-fill.svg
	folderFill: number;
	// folder-symlink-fill.svg
	folderSymlinkFill: number;
	// folder-symlink.svg
	folderSymlink: number;
	// folder.svg
	folder: number;
	// fonts.svg
	fonts: number;
	// forward-fill.svg
	forwardFill: number;
	// forward.svg
	forward: number;
	// gear-fill.svg
	gearFill: number;
	// gear-wide-connected.svg
	gearWideConnected: number;
	// gear-wide.svg
	gearWide: number;
	// gear.svg
	gear: number;
	// geo.svg
	geo: number;
	// graph-down.svg
	graphDown: number;
	// graph-up.svg
	graphUp: number;
	// grid-fill.svg
	gridFill: number;
	// grid.svg
	grid: number;
	// hammer.svg
	hammer: number;
	// hash.svg
	hash: number;
	// heart-fill.svg
	heartFill: number;
	// heart.svg
	heart: number;
	// house-fill.svg
	houseFill: number;
	// house.svg
	house: number;
	// image-alt.svg
	imageAlt: number;
	// image-fill.svg
	imageFill: number;
	// image.svg
	image: number;
	// images.svg
	images: number;
	// inbox-fill.svg
	inboxFill: number;
	// inbox.svg
	inbox: number;
	// inboxes-fill.svg
	inboxesFill: number;
	// inboxes.svg
	inboxes: number;
	// info-fill.svg
	infoFill: number;
	// info-square-fill.svg
	infoSquareFill: number;
	// info-square.svg
	infoSquare: number;
	// info.svg
	info: number;
	// justify-left.svg
	justifyLeft: number;
	// justify-right.svg
	justifyRight: number;
	// justify.svg
	justify: number;
	// kanban-fill.svg
	kanbanFill: number;
	// kanban.svg
	kanban: number;
	// laptop.svg
	laptop: number;
	// layout-sidebar-reverse.svg
	layoutSidebarReverse: number;
	// layout-sidebar.svg
	layoutSidebar: number;
	// layout-split.svg
	layoutSplit: number;
	// list-check.svg
	listCheck: number;
	// list-ol.svg
	listOl: number;
	// list-task.svg
	listTask: number;
	// list-ul.svg
	listUl: number;
	// list.svg
	list: number;
	// lock-fill.svg
	lockFill: number;
	// lock.svg
	lock: number;
	// map.svg
	map: number;
	// mic.svg
	mic: number;
	// moon.svg
	moon: number;
	// music-player-fill.svg
	musicPlayerFill: number;
	// music-player.svg
	musicPlayer: number;
	// option.svg
	option: number;
	// outlet.svg
	outlet: number;
	// pause-fill.svg
	pauseFill: number;
	// pause.svg
	pause: number;
	// pen.svg
	pen: number;
	// pencil.svg
	pencil: number;
	// people-fill.svg
	peopleFill: number;
	// people.svg
	people: number;
	// person-fill.svg
	personFill: number;
	// person.svg
	person: number;
	// phone-landscape.svg
	phoneLandscape: number;
	// phone.svg
	phone: number;
	// pie-chart-fill.svg
	pieChartFill: number;
	// pie-chart.svg
	pieChart: number;
	// play-fill.svg
	playFill: number;
	// play.svg
	play: number;
	// plug.svg
	plug: number;
	// plus.svg
	plus: number;
	// power.svg
	power: number;
	// question-fill.svg
	questionFill: number;
	// question-square-fill.svg
	questionSquareFill: number;
	// question-square.svg
	questionSquare: number;
	// question.svg
	question: number;
	// reply-all-fill.svg
	replyAllFill: number;
	// reply-all.svg
	replyAll: number;
	// reply-fill.svg
	replyFill: number;
	// reply.svg
	reply: number;
	// screwdriver.svg
	screwdriver: number;
	// search.svg
	search: number;
	// shield-fill.svg
	shieldFill: number;
	// shield-lock-fill.svg
	shieldLockFill: number;
	// shield-lock.svg
	shieldLock: number;
	// shield-shaded.svg
	shieldShaded: number;
	// shield.svg
	shield: number;
	// shift-fill.svg
	shiftFill: number;
	// shift.svg
	shift: number;
	// skip-backward-fill.svg
	skipBackwardFill: number;
	// skip-backward.svg
	skipBackward: number;
	// skip-end-fill.svg
	skipEndFill: number;
	// skip-end.svg
	skipEnd: number;
	// skip-forward-fill.svg
	skipForwardFill: number;
	// skip-forward.svg
	skipForward: number;
	// skip-start-fill.svg
	skipStartFill: number;
	// skip-start.svg
	skipStart: number;
	// speaker.svg
	speaker: number;
	// square-fill.svg
	squareFill: number;
	// square-half.svg
	squareHalf: number;
	// square.svg
	square: number;
	// star-fill.svg
	starFill: number;
	// star-half.svg
	starHalf: number;
	// star.svg
	star: number;
	// stop-fill.svg
	stopFill: number;
	// stop.svg
	stop: number;
	// stopwatch-fill.svg
	stopwatchFill: number;
	// stopwatch.svg
	stopwatch: number;
	// sun.svg
	sun: number;
	// table.svg
	table: number;
	// tablet-landscape.svg
	tabletLandscape: number;
	// tablet.svg
	tablet: number;
	// tag-fill.svg
	tagFill: number;
	// tag.svg
	tag: number;
	// terminal-fill.svg
	terminalFill: number;
	// terminal.svg
	terminal: number;
	// text-center.svg
	textCenter: number;
	// text-indent-left.svg
	textIndentLeft: number;
	// text-indent-right.svg
	textIndentRight: number;
	// text-left.svg
	textLeft: number;
	// text-right.svg
	textRight: number;
	// three-dots-vertical.svg
	threeDotsVertical: number;
	// three-dots.svg
	threeDots: number;
	// toggle-off.svg
	toggleOff: number;
	// toggle-on.svg
	toggleOn: number;
	// toggles.svg
	toggles: number;
	// tools.svg
	tools: number;
	// trash-fill.svg
	trashFill: number;
	// trash.svg
	trash: number;
	// triangle-fill.svg
	triangleFill: number;
	// triangle-half.svg
	triangleHalf: number;
	// triangle.svg
	triangle: number;
	// trophy.svg
	trophy: number;
	// tv-fill.svg
	tvFill: number;
	// tv.svg
	tv: number;
	// type-bold.svg
	typeBold: number;
	// type-h1.svg
	typeH1: number;
	// type-h2.svg
	typeH2: number;
	// type-h3.svg
	typeH3: number;
	// type-italic.svg
	typeItalic: number;
	// type-strikethrough.svg
	typeStrikethrough: number;
	// type-underline.svg
	typeUnderline: number;
	// type.svg
	type: number;
	// unlock-fill.svg
	unlockFill: number;
	// unlock.svg
	unlock: number;
	// upload.svg
	upload: number;
	// volume-down-fill.svg
	volumeDownFill: number;
	// volume-down.svg
	volumeDown: number;
	// volume-mute-fill.svg
	volumeMuteFill: number;
	// volume-mute.svg
	volumeMute: number;
	// volume-up-fill.svg
	volumeUpFill: number;
	// volume-up.svg
	volumeUp: number;
	// wallet.svg
	wallet: number;
	// watch.svg
	watch: number;
	// wifi.svg
	wifi: number;
	// window.svg
	window: number;
	// wrench.svg
	wrench: number;
	// x-circle-fill.svg
	xCircleFill: number;
	// x-circle.svg
	xCircle: number;
	// x-octagon-fill.svg
	xOctagonFill: number;
	// x-octagon.svg
	xOctagon: number;
	// x-square-fill.svg
	xSquareFill: number;
	// x-square.svg
	xSquare: number;
	// x.svg
	x: number;
}